export const BOARD_FETCH_REQUEST = "BOARD_FETCH_REQUEST";
export const BOARD_FETCH_SUCCESS = "BOARD_FETCH_SUCCESS";
export const BOARD_FETCH_ERROR = "BOARD_FETCH_ERROR";
export const ARTICLE_FETCH_REQUEST = "ARTICLE_FETCH_REQUEST";
export const ARTICLE_FETCH_SUCCESS = "ARTICLE_FETCH_SUCCESS";
export const ARTICLE_FETCH_ERROR = "ARTICLE_FETCH_ERROR"
