# ./.tmuxinator.yml

name: weatherweb
root: ./

windows:
  - git:
      layout: main-vertical
      panes:
        - git status
  - kafka: 
      layout: main-vertical
      pre: cd kafka
      panes:
          - sudo docker-compose up -d && sudo docker-compose logs -f
  # - logs: tail -f log/development.log
