# ./.tmuxinator.yml

name: project
root: ./

windows:
  - main:
      layout: main-horizontal
      panes:
          - ./up.sh && exit
  - kafka: 
      layout: main-horizontal   
      panes:
          - docker logs -f webpractice_kafka_1
          - docker logs -f webpractice_zookeeper_1
  - mariadb:
      layout: main-horizontal
      panes:
          - docker logs -f webpractice_mariadb_1
  - nginx:
      layout: main-horizontal
      panes:
          - docker logs -f webpractice_nginx_1
  # - logs: tail -f log/development.log
