# ./.tmuxinator.yml

name: project
root: ./

windows:
#   - git:
#       layout: main-horizontal
#       panes:
#         - git status
  - kafka: 
      layout: main-horizontal
      pre: cd kafka
      panes:
          - sudo docker-compose up -d && sudo docker-compose logs -f
  - mariadb:
      layout: main-horizontal
      pre: cd dbserver
      panes:
          - sudo docker-compose up -d && sudo docker-compose logs -f
  - nginx:
      layout: main-horizontal
      pre: cd nginx
      panes:
          - sudo docker-compose up -d && sudo docker-compose logs -f
  # - logs: tail -f log/development.log
