version: "3.7"

services:
  api:
    environment: 
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=webpracticedb
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
  
  mariadb:
    image: mariadb:10.5.8
    container_name: db_maria
    volumes:
      - maria_data:/var/lib/mysql
      - ./db/config:/etc/mysql
      - ./db/sql/:/docker-entrypoint-initdb.d/
    environment: 
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=webpracticedb
    ports:
      - 33010:3306

volumes:
  maria_data:
