version: "3.7"

services:
  api:
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=webpracticedb
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306

  mariadb:
    image: mariadb:10.5.8
    volumes:
      - maria_data:/var/lib/mysql
      - ./db/config:/etc/mysql
      - ./db/sql/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=webpracticedb
    ports:
      - 33010:3306

  react:
    command: npm start
    volumes:
      - ./react/board_app:/www
      - react_node_modules:/www/node_modules

volumes:
  maria_data:
  react_node_modules:
